# Generated by Django 5.0.7 on 2024-07-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0005_tag_order_customer_order_product_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='chapter.tag'),
        ),
    ]
