# Generated by Django 5.0.7 on 2024-07-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0006_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
