# Generated by Django 5.0.7 on 2024-07-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
