# Generated by Django 5.0.7 on 2024-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techers',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
