# Generated by Django 5.0.7 on 2024-07-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0014_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='page',
            new_name='note',
        ),
    ]
