# Generated by Django 5.0.7 on 2024-07-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0015_rename_page_note_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='name',
        ),
    ]
