# Generated by Django 5.0.7 on 2024-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0015_techers_phone_alter_students_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='class_room',
        ),
        migrations.AlterField(
            model_name='students',
            name='stage',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Medel', 'Medel'), ('Scondary', 'Scondary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='type',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='techers',
            name='type',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
