# Generated by Django 5.0.7 on 2024-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0016_remove_students_class_room_alter_students_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
