# Generated by Django 5.0.7 on 2024-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0017_students_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='techers',
            name='majour',
        ),
        migrations.AddField(
            model_name='techers',
            name='specialization',
            field=models.CharField(choices=[('Science', 'Science'), ('Mathematics', 'Mathematics'), ('Arabic', 'Arabic'), ('English', 'English'), ('history', 'history'), ('sport', 'sport')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='stage',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Middle ', 'Middle '), ('Secondary', 'Secondary')], max_length=50),
        ),
    ]
