# Generated by Django 5.0.7 on 2024-09-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0018_remove_students_rate_remove_techers_majour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapter.students')),
                ('techers', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapter.techers')),
            ],
        ),
    ]
