# Generated by Django 5.0.7 on 2024-09-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0019_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.AddField(
            model_name='students',
            name='class_Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapter.classes'),
        ),
    ]
