# Generated by Django 5.0.6 on 2024-09-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0021_students_amount_students_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
