# Generated by Django 5.0.6 on 2024-09-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0022_students_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
    ]
