# Generated by Django 5.0.6 on 2024-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0023_remove_students_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='class_Room',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
        migrations.AddField(
            model_name='techers',
            name='Salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='techers',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
