# Generated by Django 5.0.6 on 2024-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0025_students_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
