# Generated by Django 5.0.6 on 2024-09-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0026_alter_students_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techers',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
