# Generated by Django 5.0.6 on 2024-09-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0028_rename_age_techers_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techers',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.AlterField(
            model_name='techers',
            name='specialization',
            field=models.CharField(choices=[('Science', 'Science'), ('Mathematics', 'Mathematics'), ('Arabic', 'Arabic'), ('English', 'English'), ('history', 'history'), ('sport', 'sport'), ('Programming', 'Programming')], max_length=50, null=True),
        ),
    ]
